apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecommerce-microservices
  namespace: ecommerce
  annotations:
    iam.gke.io/gcp-service-account: ecommerce-microservices@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ecommerce-role
  namespace: ecommerce
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecommerce-rolebinding
  namespace: ecommerce
subjects:
  - kind: ServiceAccount
    name: ecommerce-microservices
    namespace: ecommerce
roleRef:
  kind: Role
  name: ecommerce-role
  apiGroup: rbac.authorization.k8s.io
